name: ai2thor-objectnav
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - setuptools
  - wheel
  - numpy<2
  - scipy
  - pandas
  - matplotlib
  - pillow
  - opencv
  - networkx
  - pyyaml
  - tqdm
  - ipykernel
  - pip:
      - --extra-index-url https://download.pytorch.org/whl/cpu
      - torch==1.10.2+cpu
      - torchvision==0.11.3+cpu
      - ai2thor==5.0.0
      - procthor==0.0.1.dev2
